import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Layout负责的是页面的整体布局，可以被多个Page公用相同的Layout */}
      {/* {children} 指代的是Page中定义的内容 */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
